//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRESEP.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoLaboral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoLaboral()
        {
            this.infoLaboral_perfilProfesional = new HashSet<infoLaboral_perfilProfesional>();
        }
    
        public int idInfoLaboral { get; set; }
        public string profesion { get; set; }
       // public Nullable<int> tiempoExperiencia { get; set; }
        public int tiempoExperiencia { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoLaboral_perfilProfesional> infoLaboral_perfilProfesional { get; set; }
    }
}
