//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRESEP.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoEstudios_perfilProfesional
    {
        public int idEstudiosProfesional { get; set; }
        public Nullable<int> idEstudios { get; set; }
        public Nullable<int> idPerfilProfesional { get; set; }
    
        public virtual InfoEstudios InfoEstudios { get; set; }
        public virtual PerfilPersona PerfilPersona { get; set; }
    }
}
