//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRESEP.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoEstudios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoEstudios()
        {
            this.infoEstudios_perfilProfesional = new HashSet<infoEstudios_perfilProfesional>();
        }
    
        public int idEstudios { get; set; }
        public Nullable<int> idGradoEstudio { get; set; }
        public Nullable<int> idInstitucion { get; set; }
        public Nullable<int> idCarrera { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoEstudios_perfilProfesional> infoEstudios_perfilProfesional { get; set; }
        public virtual InfoGradoEstudio InfoGradoEstudio { get; set; }
        public virtual InfoInstitucion InfoInstitucion { get; set; }
    }
}
